"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.leaveGallery = exports.allItemPhotos = exports.next = exports.prev = exports.characterTypeNovelties = exports.characterTypeBigDoll = exports.characterTypeUniversal = exports.characterTypeFemale = exports.characterTypeMale = exports.characterTypeAll = exports.masterClassesPoint = exports.additionsPoint = exports.programsPoint = exports.showsPoint = exports.charactersPoint = exports.mainPagePoint = exports.pageSize = exports.findNumberPageOnPage = exports.findCurrentType = exports.findCurrentCharacter = exports.findCurrentPage = exports.urlTgCheck = exports.urlCheck = exports.secretWordDetail = exports.secretWordGeneral = exports.managerId = exports.managerNumber = exports.stickerCatInGlasses = exports.stickerHippo = exports.stickerMole = exports.stickerCat = exports.stickerBear = void 0;
exports.stickerBear = 'CAACAgIAAxkBAAEFd9xmRe_QqkSdLK4zEmw8cds6bvSSPwAC_AAD9wLID-JKwmellSruNQQ';
exports.stickerCat = 'CAACAgIAAxkBAAEF4vdmXtkK9WzTLlntl-SOA4XH4BCpbAACbwADmL-ADeFz2TIaBadINQQ';
exports.stickerMole = 'CAACAgIAAxkBAAEF4vlmXtkjDQ8OCbPmmiYuKiFAK0QMjgACQQADr8ZRGpJsDHTQJyI-NQQ';
exports.stickerHippo = 'CAACAgIAAxkBAAEF4vtmXtlEFvB9fj9ibmDSrIu2m9gIlAACNQEAAjDUnRG0uDX9ZqC2fDUE';
exports.stickerCatInGlasses = 'CAACAgQAAxkBAAEF4wVmXtmCV0WhBfaNWj1GTWDjZIdlbgAC2wcAAm2XuFGYPUTyal0iaDUE';
exports.managerNumber = '375293030068';
exports.managerId = '917868899';
exports.secretWordGeneral = 'getInformationGeneral';
exports.secretWordDetail = 'getInformationDetail';
exports.urlCheck = /^http/gi;
exports.urlTgCheck = /^tg/gi;
exports.findCurrentPage = /(?<=_)\d+/;
exports.findCurrentCharacter = /(?<=_)[a-zA-Z]+/;
exports.findCurrentType = /[a-zA-Z]+(?=_)/;
exports.findNumberPageOnPage = /(?<=Страница\s)\d+/;
exports.pageSize = 8;
exports.mainPagePoint = 'mainPage';
exports.charactersPoint = 'characters';
exports.showsPoint = 'shows';
exports.programsPoint = 'programs';
exports.additionsPoint = 'additions';
exports.masterClassesPoint = 'masterClasses';
exports.characterTypeAll = 'all';
exports.characterTypeMale = 'male';
exports.characterTypeFemale = 'female';
exports.characterTypeUniversal = 'universal';
exports.characterTypeBigDoll = 'bigDoll';
exports.characterTypeNovelties = 'novelties';
exports.prev = 'prev';
exports.next = 'next';
exports.allItemPhotos = 'allPhotos';
exports.leaveGallery = 'leaveGallery';
