"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.masterClassesMenu = exports.additionsMenu = exports.programsMenu = exports.showsMenu = exports.itemMenu = exports.charactersMenu = exports.characters = void 0;
const constants_1 = require("./constants");
;
exports.characters = [
    ['Маршал', 'marshall', { flag: constants_1.characterTypeUniversal }],
    ['Гончик', 'chase', { flag: constants_1.characterTypeMale }],
    ['Скай', 'skye', { flag: constants_1.characterTypeFemale }],
    ['Человек паук', 'spiderMan', { flag: constants_1.characterTypeMale }],
    ['Бэтмен', 'batMan', { flag: constants_1.characterTypeMale }],
    ['Халк', 'hulk', { flag: constants_1.characterTypeMale }],
    ['Железный человек', 'ironMan', { flag: constants_1.characterTypeMale }],
    ['Супердевушка', 'superWoman', { flag: constants_1.characterTypeFemale }],
    ['Черепашка ниндзя', 'ninjaTurtle', { flag: constants_1.characterTypeMale }],
    ['Соник', 'sonic', { flag: constants_1.characterTypeMale }],
    ['Ниндзяго', 'ninjago', { flag: constants_1.characterTypeUniversal }],
    ['Алетт', 'alette', { flag: constants_1.characterTypeFemale }],
    ['Амонг Ас', 'amongUs', { flag: constants_1.characterTypeUniversal }],
    ['Русалочка', 'mermaid', { flag: constants_1.characterTypeFemale }],
    ['Динозавр зубастик', 'dinosaurToothy', { flag: constants_1.characterTypeMale }],
    ['Мистер кошмариус', 'misterNightmareous', { flag: constants_1.characterTypeMale }],
    ['Исследователь', 'researcher', { flag: constants_1.characterTypeFemale }],
    ['Клоун Ляля', 'clownLala', { flag: constants_1.characterTypeFemale }],
    ['Кукла Лол', 'lolDoll', { flag: constants_1.characterTypeFemale }],
    ['Майнкрафт', 'minecraft', { flag: constants_1.characterTypeUniversal }],
    ['Маша', 'masha', { flag: constants_1.characterTypeFemale }],
    ['Миньон', 'minions', { flag: constants_1.characterTypeUniversal }],
    ['Зайка', 'bunny', { flag: constants_1.characterTypeBigDoll }],
    ['Мишка', 'bear', { flag: constants_1.characterTypeBigDoll }],
    ['Бегемотик', 'hippo', { flag: constants_1.characterTypeBigDoll }],
    ['Мишутка коричневый', 'bearBrown', { flag: constants_1.characterTypeBigDoll }],
    ['Мишутка розовый', 'bearPink', { flag: constants_1.characterTypeBigDoll }],
    ['Олаф', 'snowmanOlaf', { flag: constants_1.characterTypeBigDoll }],
    ['Барби и Кен', 'barbieAndKen', { flag: constants_1.characterTypeFemale }],
    ['Индейцы', 'indians', { flag: constants_1.characterTypeUniversal }],
    ['Леди Баг и Супер Кот', 'ladyBugAndSuperCat', { flag: constants_1.characterTypeUniversal }],
    ['Минни Маус', 'minnieMouse', { flag: constants_1.characterTypeFemale }],
    ['Принц и Ариэль', 'princeAndAriel', { flag: constants_1.characterTypeUniversal }],
    ['Ёжик Вячеслав', 'hedgehogVyacheslav', { flag: constants_1.characterTypeUniversal }],
    ['Моана', 'moana', { flag: constants_1.characterTypeFemale }],
    ['Молния Маквин', 'lightningMCQUEEN', { flag: constants_1.characterTypeMale }],
    ['Нюшенька', 'nyushenka', { flag: constants_1.characterTypeFemale }],
    ['Петронелла', 'petronella', { flag: constants_1.characterTypeFemale }],
    ['Пиратка Мэри', 'pirateMary', { flag: constants_1.characterTypeFemale }],
    ['Пират', 'pirate', { flag: constants_1.characterTypeMale }],
    ['Пираты', 'pirates', { flag: constants_1.characterTypeUniversal }],
    ['Подруга Уэнсдей', 'girlfriendWednesday', { flag: constants_1.characterTypeFemale }],
    ['Помни', 'remember', { flag: constants_1.characterTypeFemale }],
    ['Принцесса Жасмин', 'princessJasmine', { flag: constants_1.characterTypeFemale }],
    ['Единорожка Искорка', 'unicornSparkle', { flag: constants_1.characterTypeFemale }],
    ['Пинки Пай', 'pinkiePie', { flag: constants_1.characterTypeFemale }],
    ['Принцесса Селестия', 'princessCelestia', { flag: constants_1.characterTypeFemale }],
    ['Робокар Полли', 'robocarPoli', { flag: constants_1.characterTypeMale }],
    ['Робокар Эмбер', 'robocarAmber', { flag: constants_1.characterTypeFemale }],
    ['Свинка Пеппа', 'peppaPig', { flag: constants_1.characterTypeFemale }],
    ['Синий трактор', 'blueTractor', { flag: constants_1.characterTypeUniversal }],
    ['Тик Ток', 'tikTok', { flag: constants_1.characterTypeUniversal }],
    ['Котёнок Коржик', 'kittenKorzhik', { flag: constants_1.characterTypeMale }],
    ['Кошечка Карамелька', 'kittyCaramel', { flag: constants_1.characterTypeFemale }],
    ['Котёнок Компот', 'kittenCompote', { flag: constants_1.characterTypeMale }],
    ['Тролль', 'troll', { flag: constants_1.characterTypeFemale }],
    ['Умный профессор', 'smartProfessor', { flag: constants_1.characterTypeUniversal }],
    ['Уэнсдей', 'wednesday', { flag: constants_1.characterTypeFemale }],
    ['Фьёк', 'fjok', { flag: constants_1.characterTypeUniversal }],
    ['Фея', 'faerie', { flag: constants_1.characterTypeFemale }],
    ['Фиксики', 'fixies', { flag: constants_1.characterTypeUniversal }],
    ['Анна', 'anna', { flag: constants_1.characterTypeFemale }],
    ['Эльза', 'elsa', { flag: constants_1.characterTypeFemale }],
    ['Ведьмочка Винни', 'winnieTheWitch', { flag: constants_1.characterTypeFemale }],
    ['Ви', 'vi', { flag: constants_1.characterTypeFemale }],
    ['Шелли brawl stars', 'shelleyBrawlStars', { flag: constants_1.characterTypeFemale }],
    ['Чебурашка', 'cheburashka', { flag: constants_1.characterTypeUniversal }],
    ['Шкодники', 'mischiefMakers', { flag: constants_1.characterTypeUniversal }],
];
exports.charactersMenu = [
    ['🎁 Все', constants_1.characterTypeAll],
    ['👧 Женские образы', constants_1.characterTypeFemale],
    ['👦 Mужские образы', constants_1.characterTypeMale],
    ['👫 Универсальные образы', constants_1.characterTypeUniversal],
    ['🐥 Ростовые куклы', constants_1.characterTypeBigDoll],
];
exports.itemMenu = [
    ['◀◀ Пред.', 'prev'],
    ['След. ▶▶', 'next'],
    // ['Все фото', 'allPhotos'],
    ['📞 Связаться с нами', `https://viber.click/${constants_1.managerNumber}`],
];
exports.showsMenu = [
    ['🎁 Серебряная дискотека', 'silverDisco'],
    ['🎁 Поролоновое шоу', 'foamShow'],
    ['🎁 Мыльное шоу', 'soapShow'],
    ['🎁 Азотное шоу', 'nitrogenShow'],
    ['🎁 Надувное шоу', 'inflatableShow'],
    ['🎁 Неоновое шоу', 'neonShow'],
];
exports.programsMenu = [
    ['📓 Поздравление от ростовой куклы', 'programs_congratulationFromBigDoll'],
    ['📓 Экспресс-поздравление', 'programs_expressCongratulations'],
    ['📓 Мини', 'programs_mini'],
    ['📓 Компакт', 'programs_compact'],
    ['📓 Вау', 'programs_wow'],
    ['📓 Супер', 'programs_super'],
    ['📓 Слабо-шоу', 'programs_challengeShow'],
    ['📓 Блестящий праздник', 'programs_brilliantHoliday'],
    ['📓 Умный праздник', 'programs_smartHoliday'],
    ['📓 Тематический квест', 'programs_thematicQuest'],
    ['📓 Пузыряши', 'programs_bubbles'],
    ['📓 Сборная программа', 'programs_customProgram'],
];
exports.additionsMenu = [
    ['🏷️ Аниматор-няня', 'additions_animatorNanny'],
    ['🏷️ Игровые зоны', 'additions_playAreas'],
    ['🏷️ Пиньята', 'additions_pinata'],
    ['🏷️ Погружение в пузырь', 'additions_diveIntoTheBubble'],
    ['🏷️ Шар-сюрприз', 'additions_ballSurprise'],
    ['🏷️ Дымный эффект', 'additions_smokeEffect'],
    ['🏷️ Конфетти', 'additions_confetti'],
    ['🏷️ Фотозоны', 'additions_photoZones'],
    ['🏷️ Фото, видеоуслуги', 'additions_photoVideoServices'],
];
exports.masterClassesMenu = [
    ['🪁 Праздничные открытки', 'masterClasses_holidayCards'],
    ['🪁 Слаймы', 'masterClasses_slimes'],
    ['🪁 Маски из фоамирана', 'masterClasses_foamiranMasks'],
    ['🪁 Паровые коктейли', 'masterClasses_steamCocktails'],
    ['🪁 Мороженое', 'masterClasses_iceCream'],
    ['🪁 Роспись деревянных магнитов', 'masterClasses_paintingWoodenMagnets'],
    ['🪁 Деревянные подставки', 'masterClasses_woodenCoasters'],
    ['🪁 Роспись гипсовых фигурок', 'masterClasses_paintingPlasterFigures'],
    ['🪁 Роспись футболок', 'masterClasses_tShirtPainting'],
    ['🪁 Твистинг', 'masterClasses_twisting'],
    ['🪁 Украшения из фигурных макарон', 'masterClasses_decorationsMadeFromCurlyPasta'],
    ['🪁 Украшения из бусин', 'masterClasses_beadJewelry'],
    ['🪁 Мыльные пузыри', 'masterClasses_soapBubbles'],
    ['🪁 Роспись масок из папье-маше', 'masterClasses_paintingPapierMacheMasks'],
    ['🪁 Эбру - рисование на воде', 'masterClasses_ebruPaintingOnWater'],
];
