import {
    managerNumber,
    managerId,
    characterTypeAll,
    characterTypeMale,
    characterTypeFemale,
    characterTypeUniversal,
    characterTypeBigDoll
} from "./constants";

export interface ICharactersFlag {
    flag: string;
};

export const characters: (string | ICharactersFlag)[][] = [
    ['Маршал', 'marshall', {flag: characterTypeUniversal}],
    ['Гончик', 'chase', {flag: characterTypeMale}],
    ['Скай', 'skye', {flag: characterTypeFemale}],
    ['Человек паук', 'spiderMan', {flag: characterTypeMale}],
    ['Бэтмен', 'batMan', {flag: characterTypeMale}],
    ['Халк', 'hulk', {flag: characterTypeMale}],
    ['Железный человек', 'ironMan', {flag: characterTypeMale}],
    ['Супердевушка', 'superWoman', {flag: characterTypeFemale}],
    ['Черепашка ниндзя', 'ninjaTurtle', {flag: characterTypeMale}],
    ['Соник', 'sonic', {flag: characterTypeMale}],
    ['Ниндзяго', 'ninjago', {flag: characterTypeUniversal}],
    ['Алетт', 'alette', {flag: characterTypeFemale}],
    ['Амонг Ас', 'amongUs', {flag: characterTypeUniversal}],
    ['Русалочка', 'mermaid', {flag: characterTypeFemale}],
    ['Динозавр зубастик', 'dinosaurToothy', {flag: characterTypeMale}],
    ['Мистер кошмариус', 'misterNightmareous', {flag: characterTypeMale}],
    ['Исследователь', 'researcher', {flag: characterTypeFemale}],
    ['Клоун Ляля', 'clownLala', {flag: characterTypeFemale}],
    ['Кукла Лол', 'lolDoll', {flag: characterTypeFemale}],
    ['Майнкрафт', 'minecraft', {flag: characterTypeUniversal}],
    ['Маша', 'masha', {flag: characterTypeFemale}],
    ['Миньон', 'minions', {flag: characterTypeUniversal}],
    ['Зайка', 'bunny', {flag: characterTypeBigDoll}],
    ['Мишка', 'bear', {flag: characterTypeBigDoll}],
    ['Бегемотик', 'hippo', {flag: characterTypeBigDoll}],
    ['Мишутка коричневый', 'bearBrown', {flag: characterTypeBigDoll}],
    ['Мишутка розовый', 'bearPink', {flag: characterTypeBigDoll}],
    ['Олаф', 'snowmanOlaf', {flag: characterTypeBigDoll}],
    ['Барби и Кен', 'barbieAndKen', {flag: characterTypeUniversal}],
    ['Индейцы', 'indians', {flag: characterTypeUniversal}],
    ['Леди Баг и Супер Кот', 'ladyBugAndSuperCat', {flag: characterTypeUniversal}],
    ['Минни Маус', 'minnieMouse', {flag: characterTypeFemale}],
    ['Принц и Ариэль', 'princeAndAriel', {flag: characterTypeUniversal}],
    ['Ёжик Вячеслав', 'hedgehogVyacheslav', {flag: characterTypeUniversal}],
    ['Моана', 'moana', {flag: characterTypeFemale}],
    ['Молния Маквин', 'lightningMCQUEEN', {flag: characterTypeMale}],
    ['Нюшенька', 'nyushenka', {flag: characterTypeFemale}],
    ['Петронелла', 'petronella', {flag: characterTypeFemale}],
    ['Пиратка Мэри', 'pirateMary', {flag: characterTypeFemale}],
    ['Пират', 'pirate', {flag: characterTypeMale}],
    ['Пираты', 'pirates', {flag: characterTypeUniversal}],
    ['Подруга Уэнсдей', 'girlfriendWednesday', {flag: characterTypeFemale}],
    ['Помни', 'remember', {flag: characterTypeFemale}],
    ['Принцесса Жасмин', 'princessJasmine', {flag: characterTypeFemale}],
    ['Единорожка Искорка', 'unicornSparkle', {flag: characterTypeFemale}],
    ['Пинки Пай', 'pinkiePie', {flag: characterTypeFemale}],
    ['Принцесса Селестия', 'princessCelestia', {flag: characterTypeFemale}],
    ['Робокар Полли', 'robocarPoli', {flag: characterTypeMale}],
    ['Робокар Эмбер', 'robocarAmber', {flag: characterTypeFemale}],
    ['Свинка Пеппа', 'peppaPig', {flag: characterTypeFemale}],
    ['Синий трактор', 'blueTractor', {flag: characterTypeUniversal}],
    ['Тик Ток', 'tikTok', {flag: characterTypeUniversal}],
    ['Котёнок Коржик', 'kittenKorzhik', {flag: characterTypeMale}],
    ['Кошечка Карамелька', 'kittyCaramel', {flag: characterTypeFemale}],
    ['Котёнок Компот', 'kittenCompote', {flag: characterTypeMale}],
    ['Тролль', 'troll', {flag: characterTypeFemale}],
    ['Умный профессор', 'smartProfessor', {flag: characterTypeUniversal}],
    ['Уэнсдей', 'wednesday', {flag: characterTypeFemale}],
    ['Фьёк', 'fjok', {flag: characterTypeUniversal}],
    ['Фея', 'faerie', {flag: characterTypeFemale}],
    ['Фиксики', 'fixies', {flag: characterTypeUniversal}],
    ['Анна', 'anna', {flag: characterTypeFemale}],
    ['Эльза', 'elsa', {flag: characterTypeFemale}],
    ['Ведьмочка Винни', 'winnieTheWitch', {flag: characterTypeFemale}],
    ['Ви', 'vi', {flag: characterTypeFemale}],
    ['Шелли brawl stars', 'shelleyBrawlStars', {flag: characterTypeFemale}],
    ['Чебурашка', 'cheburashka', {flag: characterTypeUniversal}],
    ['Шкодники', 'mischiefMakers', {flag: characterTypeUniversal}],
    ['Бамблби', 'bumblebee', {flag: characterTypeMale}],
    ['Гарри Поттер и Гермиона', 'harryPotterAndHermione', {flag: characterTypeUniversal}],
    ['Малефисента', 'maleficent', {flag: characterTypeFemale}],
    ['Марио', 'mario', {flag: characterTypeMale}],
    ['Гринч', 'grinch', {flag: characterTypeMale}],
    ['Баба Яга', 'babaYaga', {flag: characterTypeUniversal}],
    ['Кейн', 'kane', {flag: characterTypeMale}],
    ['Буба', 'booba', {flag: characterTypeUniversal}],
];

export const charactersMenu: string[][] = [
    ['🎁 Все', characterTypeAll],
    ['👧 Женские образы', characterTypeFemale],
    ['👦 Mужские образы', characterTypeMale],
    ['👫 Универсальные образы', characterTypeUniversal],
    ['🐥 Ростовые куклы', characterTypeBigDoll],
    ['🤗 Больше фото', 'https://disk.yandex.ru/d/N7C7ts1D9fCvgg'],
];

export const itemMenu: string[][] = [
    ['◀◀ Пред. фото', 'prev'],
    ['След. фото ▶▶', 'next'],
    ['📞Связаться(viber)', `https://viber.click/${managerNumber}`],
    ['📞Связаться(telegram)', `tg://user?id=${managerId}`],
];

export const showsMenu: string[][] = [
    ['🎁 Серебряная дискотека', 'silverDisco'],
    ['🎁 Поролоновое шоу', 'foamShow'],
    ['🎁 Мыльное шоу', 'soapShow'],
    ['🎁 Азотное шоу', 'nitrogenShow'],
    ['🎁 Надувное шоу', 'inflatableShow'],
    ['🎁 Неоновое шоу', 'neonShow'],
];

export const programsMenu: string[][] = [
    ['📓 Поздравление от ростовой куклы', 'programs_congratulationFromBigDoll'],
    ['📓 Экспресс-поздравление', 'programs_expressCongratulations'],
    ['📓 Мини', 'programs_mini'],
    ['📓 Компакт', 'programs_compact'],
    ['📓 Вау', 'programs_wow'],
    ['📓 Супер', 'programs_super'],
    ['📓 Слабо-шоу', 'programs_challengeShow'],
    ['📓 Блестящий праздник', 'programs_brilliantHoliday'],
    ['📓 Умный праздник', 'programs_smartHoliday'],
    ['📓 Тематический квест', 'programs_thematicQuest'],
    ['📓 Пузыряши', 'programs_bubbles'],
    ['📓 Сборная программа', 'programs_customProgram'],
];

export const additionsMenu: string[][] = [
    ['🏷️ Аниматор-няня', 'additions_animatorNanny'],
    ['🏷️ Игровые зоны', 'additions_playAreas'],
    ['🏷️ Пиньята', 'additions_pinata'],
    ['🏷️ Погружение в пузырь', 'additions_diveIntoTheBubble'],
    ['🏷️ Шар-сюрприз', 'additions_ballSurprise'],
    ['🏷️ Дымный эффект', 'additions_smokeEffect'],
    ['🏷️ Конфетти', 'additions_confetti'],
    ['🏷️ Фотозоны', 'additions_photoZones'],
    ['🏷️ Фото, видеоуслуги', 'additions_photoVideoServices'],
];

export const masterClassesMenu: string[][] = [
    ['🪁 Праздничные открытки', 'masterClasses_holidayCards'],
    ['🪁 Слаймы', 'masterClasses_slimes'],
    ['🪁 Маски из фоамирана', 'masterClasses_foamiranMasks'],
    ['🪁 Паровые коктейли', 'masterClasses_steamCocktails'],
    ['🪁 Мороженое', 'masterClasses_iceCream'],
    ['🪁 Роспись деревянных магнитов', 'masterClasses_paintingWoodenMagnets'],
    ['🪁 Деревянные подставки', 'masterClasses_woodenCoasters'],
    ['🪁 Роспись гипсовых фигурок', 'masterClasses_paintingPlasterFigures'],
    ['🪁 Роспись футболок', 'masterClasses_tShirtPainting'],
    ['🪁 Твистинг', 'masterClasses_twisting'],
    ['🪁 Украшения из фигурных макарон', 'masterClasses_decorationsMadeFromCurlyPasta'],
    ['🪁 Украшения из бусин', 'masterClasses_beadJewelry'],
    ['🪁 Мыльные пузыри', 'masterClasses_soapBubbles'],
    ['🪁 Роспись масок из папье-маше', 'masterClasses_paintingPapierMacheMasks'],
    ['🪁 Эбру - рисование на воде', 'masterClasses_ebruPaintingOnWater'],
];
